# Generated by Django 3.2.25 on 2024-10-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yours', '0002_auto_20241009_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
