# Generated by Django 3.2.25 on 2024-10-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yours', '0005_post_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pics'),
        ),
    ]
