# Generated by Django 3.2.25 on 2024-10-24 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yours', '0009_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['dt_created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-dt_created']},
        ),
    ]
