# Generated by Django 3.2.25 on 2024-11-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yours', '0012_auto_20241031_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
